org: carlini
app: telegram-bot-crp
service: telegram-bot-crp

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  bot:
    handler: handler.bot
    events:
      - http:
          path: /
          method: any
    environment:
      TL_TOKEN: ${param:TL_TOKEN}
      RAPIDAPI_KEY: ${param:RAPIDAPI_KEY}

